Algoritmo "Contar de 10 até 0"
// Disciplina  : Curso de Algoritmo e Lógica de Programação
// Professor   : Gustavo Guanabara
// Descrição   : Contar de 10 até 0. Simples.
// Autor(a)    : Ari Melo
// Data atual  : 01/07/2018
Var
   c:inteiro
Inicio
      C<-10//A variável inicia com valor 10
      enquanto (c>=0) faca //Forma simples de fazer um contador bem famoso
           escreva(c)
           c<-c-1
      fimenquanto
Fimalgoritmo