Algoritmo "Contar de 0 até o usuário definir"
// Disciplina  : Curso de Algoritmo e Lógica de Programação
// Professor   : Gustavo Guanabara
// Descrição   : Contar de 0 até o valor que o usuário definir.
// Autor(a)    : Ari Melo
// Data atual  : 05/07/2018
Var
   c,vezes:inteiro
Inicio
      escreva("Até quanto? ")
      leia(vezes)
      c<-1
      enquanto (c<=vezes) faca
           escreva(c)
           c<-c+1
      fimenquanto
Fimalgoritmo