algoritmo "Números pares"
// Disciplina  : Curso de Algoritmo e Lógica de Programação
// Professor   : Gustavo Guanabara
// Descrição   : Entra um valor que vai ser o último de uma contagem de apenas números pares.
// Autor(a)    : Ari Melo
// Data atual  : 01/07/2018
var
   c,fim:inteiro
inicio
      escreva("Fim: ")
      leia(fim)
      
      para c<-0 ate fim passo 2 faca //Apenas números pares
           escreva(c)
      fimpara
fimalgoritmo