algoritmo "Combinações"
// Disciplina  : Curso de Algoritmo e Lógica de Programação
// Professor   : Gustavo Guanabara
// Descrição   : Matrizes, combinações de dois PARA.
// Autor(a)    : Ari Melo
// Data atual  : 01/07/2018
var
   c1,c2:inteiro
inicio
      para c1<-1 ate 3 passo 1 faca
           para c2<-1 ate 3 passo 1 faca //Um PARA dentro de outro
                escreval(c1,c2)
           fimpara
      fimpara
fimalgoritmo