Algoritmo "Contar de 0 até 10"
// Disciplina  : Curso de Algoritmo e Lógica de Programação
// Professor   : Gustavo Guanabara
// Descrição   : Irá contar de 0 até 10. Simples.
// Autor(a)    : Ari Melo
// Data atual  : 01/07/2018
Var
   c:inteiro
Inicio
      c<-0//A variável inicia em 0
      enquanto (c<=10) faca //Uma das formas mais famosas para fazer este contador
           escreva(c)
           c<-c+1
      fimenquanto
Fimalgoritmo